import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/app/components/Nav/Nav";
import {Inter } from "next/font/google";
const inter=Inter({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex p-8 ` }
      >
        <Nav/>
        <div className="mt-16 px-10">
        {children}
        </div>
      </body>
    </html>
  );
}
